---
- hosts: all
  tasks:
    - name: install dependencies
      community.docker.docker_container:
        name: npm_install
        image: node:14
        command: npm install
        working_dir: /usr/src/app
        interactive: yes
        detach: no
        volumes:
          - ./:/usr/src/app
    - name: build
      community.docker.docker_container:
        name: build
        image: node:14
        command: npm run build
        working_dir: /usr/src/app
        interactive: yes
        detach: no
        volumes:
          - ./:/usr/src/app
