---
- hosts: all
  tasks:
    - name: run build
      community.docker.docker_container:
        name: npm_install
        image: node:14
        recreate: yes
        command: ./scripts/build.sh
        working_dir: /usr/src/app
        interactive: yes
        volumes:
          - ./:/usr/src/app
